require: rubocop-rails

AllCops: 
  NewCops: disable

Bundler/OrderedGems:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false

